name: Versioning

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2

    - name: Bump version and create tag
      run: |
        git config --global user.email "jonatasmarques09@gmail.com"
        git config --global user.name "jobenevi"
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [ -z "$latest_tag" ]; then
          new_tag="v0.1.0"
        else
          new_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
        fi
        git tag $new_tag
        git push origin $new_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}